# Generated by Django 4.2.28 on 2026-03-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeedynamicdata',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='employeedynamicdata',
            constraint=models.UniqueConstraint(fields=('employee', 'field'), name='unique_employee_field'),
        ),
    ]
