# Generated by Django 4.2.28 on 2026-03-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employeedynamicdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('tel', 'Phone'), ('textarea', 'Textarea')], max_length=20),
        ),
    ]
